apiVersion: v1
kind: Namespace
metadata:
  name: acme-solver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solver-account
  namespace: acme-solver
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: acme-solver 
rules:
- apiGroups: ["acme.cert-manager.io"] 
  resources: ["challenges"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solver-read-challenges 
  namespace: acme-solver
subjects:
- kind: ServiceAccount
  name: solver-account
  namespace: acme-solver
roleRef:
  kind: ClusterRole 
  name: acme-solver 
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: acme-solver
  name: acme-solver
  labels:
    app: acme-solver
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: acme-solver
  template:
    metadata:
      labels:
        app: acme-solver
    spec:
      serviceAccountName: solver-account
      containers:
      - command:
        - /acme-solver
        - --domain=$(DOMAIN)
        - --in-cluster
        - --bind=:18853
        image: rpkatz/acme-solver:v1.1.2
        env:
        - name: DOMAIN
          value: "solver.mydomain.tld"
        imagePullPolicy: IfNotPresent
        name: acme-solver
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: acme-solver
  name: acme-solver
  labels:
    app: acme-solver
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 18853
    protocol: TCP
  selector:
    app: acme-solver
  type: NodePort

