apiVersion: v1
kind: Namespace
metadata:
        name: staging
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: certtest
  namespace: staging 
spec:
  secretName: certtest
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - test123.newdomain.fake.com
  - test456.newdomain.fake.com
